### PR TITLE
Cross-reference hidden and internal

### LINKED ISSUE #365: Can't hide a subcommand?
At https://github.com/dhall-lang/dhall-haskell/compare/sjakobi/hide-parse-tree I try to add a hidden `parse-tree` subcommand.

The subcommand parser is essentially

```
hsubparser
    (   command "parse-tree" parserInfo
    <>  metavar "parse-tree"
    <>  hidden
    )
```

Yet the `hidden` modifier doesn't seem to have any effect. The command still appears in the "Available commands" list:

```
$ cabal run -- dhall:dhall -h
...
Available commands:
...
  parse-tree               Output the parsed syntax tree (for debugging)
```

 Am I doing something something wrong?

### PR DESCRIPTION
**Pull request by sjakobi**
Closes #365.

### CODE REVIEW

File: src/Options/Applicative/Builder/Internal.hs [hunk 1]
```diff
@@ -181,5 +181,7 @@ mkProps (DefaultProp def sdef) g = props
       { propShowDefault = sdef <*> def }
 
 -- | Hide this option from the help text
+--
+-- Use 'hidden' to hide the option from the brief description too.
```
Comment (HuwCampbell) [inline src/Options/Applicative/Builder/Internal.hs]: This isn't quite right. Visibility is used as an ordered enumeration, so it's more like:

"use 'hidden' to only hide from the brief description."

Comment (HuwCampbell) [reply src/Options/Applicative/Builder/Internal.hs]: https://github.com/pcapriotti/optparse-applicative/blob/6ff428bd332af7458af93b63a523f40284049453/src/Options/Applicative/Types.hs#L140-L144

Comment (sjakobi) [reply src/Options/Applicative/Builder/Internal.hs]: Ah, thanks for clearing that up!
